---
- name: "Configuartion Cart service"
  hosts: cart
  become: yes
  tasks:
  - name: "enabling nodejs 20"
    command: "dnf module enable nodejs:20 -y"

  - name: "installing nodejs"
    dnf:
      name: nodejs
      state: present
  
  - name: "create system user roboshop"
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop user"
  
  - name: "Deleting the existing app directory"
    file:
     path: /app
     state: absent
  
  - name: "creating app directory"
    file:
      path: /app
      state: directory
  
  - name: "dowloaning cart code"
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip
  
  - name: "Extracting the code"
    unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: "installing npm dependencies"
    community.general.npm: 
      path: /app
  
  - name: "copying cart.service file"
    template:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: "starting cart service"
    service:
      name: cart
      state: restarted
      enabled: yes
