---
- name: "configuration catalogue instance"
  hosts: catalogue.swarupmacha.online
  become: yes
  tasks:
  - name:
    command: "dnf module enable nodejs:20 -y"

  - name: "Installing nodejs"
    yum:
      name: nodejs
      state: present

  - name: create system user roboshop
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop user"

  - name: "Deleting the esisting application content"
    file:
      path: /app
      state: absent

  - name: "Creating application directory"
    file:
      path: /app
      state: directory

  - name: "delete catalogue service file if exist"
    file:
      path:  /tmp/catalogue.zip
      state: absent

  - name: "Downloading catalogue code"
    get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: /tmp/catalogue.zip

  - name: "Extracting the code"
    unarchive:
      src: /tmp/catalogue.zip
      dest: /app

  - name: "Installing npm dependencies"
    community.general.npm:
      path: /app

  - name: "copying catalogue.service file"
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb client
    yum:
      name: mongodb-mongosh
      state: present
  
  - name: check products
    command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: printin the output 
    debug:
      msg: "{{  catalogue_output }}"

  - name: "Loading the catalogue schema"
    shell: "mongosh --host "{{ MONGODB_HOST }}"  </app/db/master-data.js"
    when: catalogue_output.stdout | int < 0

  - name: "staring the catalogue service"
    service:
      name: catalogue
      state: restarted
      enabled: yes
  
