---
- name: "configuration rabbitmq instance"
  hosts: rabbitmq
  become: yes
  tasks:
  - name: "copying rabbitmq repo file"
    copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
    
  - name: "Intsallling rabbutmq"
    yum: 
      name: rabbitmq-server
      state: present
  
  - name: "starting rabbitmq serrvice"
    service: 
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: "create rabbimq user"
    shell: |
      rabbitmqctl add_user roboshop roboshop123 || true
      rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"