---
- name: "configuration rabbitmq instance"
  hosts: rabbitmq
  become: yes
  tasks:
  - name: "copying rabbitmq repo file"
    copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
    
  - name: "Intsallling rabbutmq"
    yum: 
      name: rabbitmq-server
      state: present
  
  - name: "starting rabbitmq serrvice"
    service: 
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: "create rabbimq user"
    community.general.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions: 
        - vhost: /
          configure_priv: .*
          write_priv: .*
          read_priv: .*
      state: present