---
- name: "configure shipping instnace"
  hosts: shipping
  become: yes
  tasks:
  - name: "installing maven and mysql client"
    yum: 
      name: "{{ item}}"
      state: present
    loop:
      - maven
      - mysql
  
  - name: "adding shipping user"
    user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "roboshop user"

  - name: "Deleting the existing app directory"
    file:
      path: /app
      state: absent
  
  - name: "creating app directory"
    file:
      path: /app
      state: directory

  - name: "dowloanding shippig code"
    get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip
  
  - name: "Extracting the code"
    unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  
  - name: "install dependencies"
    command: "mvn clean package"
    args:
      chdir: /app

  - name: "installing dependencies"
    command: "mv target/shipping-1.0.jar shipping.jar"
    args:
      chdir: /app

  - name: "copying shipping.service file"
    temeplate:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name:  "daemon reload"
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: install dependencie
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: import shipping data
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
  

  